/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i oscann_adaptor.h -a :oscann_adaptor.cpp ../../OAOI/dbus/oscann.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "oscann_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CVInterfaceAdaptor
 */

CVInterfaceAdaptor::CVInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CVInterfaceAdaptor::~CVInterfaceAdaptor()
{
    // destructor
}

/*
 * Implementation of adaptor class CapturerInterfaceAdaptor
 */

CapturerInterfaceAdaptor::CapturerInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CapturerInterfaceAdaptor::~CapturerInterfaceAdaptor()
{
    // destructor
}

/*
 * Implementation of adaptor class DetectorInterfaceAdaptor
 */

DetectorInterfaceAdaptor::DetectorInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DetectorInterfaceAdaptor::~DetectorInterfaceAdaptor()
{
    // destructor
}

/*
 * Implementation of adaptor class DisplayCTInterfaceAdaptor
 */

DisplayCTInterfaceAdaptor::DisplayCTInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DisplayCTInterfaceAdaptor::~DisplayCTInterfaceAdaptor()
{
    // destructor
}

/*
 * Implementation of adaptor class GUIInterfaceAdaptor
 */

GUIInterfaceAdaptor::GUIInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GUIInterfaceAdaptor::~GUIInterfaceAdaptor()
{
    // destructor
}

void GUIInterfaceAdaptor::methodName()
{
    // handle method call aura.GUIInterface.methodName
    QMetaObject::invokeMethod(parent(), "methodName");
}

/*
 * Implementation of adaptor class WriterInterfaceAdaptor
 */

WriterInterfaceAdaptor::WriterInterfaceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WriterInterfaceAdaptor::~WriterInterfaceAdaptor()
{
    // destructor
}

