/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i oscann_interface.h -p :oscann_interface.cpp ../../OAOI/dbus/oscann.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "oscann_interface.h"
/*
 * Implementation of interface class AuraCVInterfaceInterface
 */

AuraCVInterfaceInterface::AuraCVInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraCVInterfaceInterface::~AuraCVInterfaceInterface()
{
}

/*
 * Implementation of interface class AuraCapturerInterfaceInterface
 */

AuraCapturerInterfaceInterface::AuraCapturerInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraCapturerInterfaceInterface::~AuraCapturerInterfaceInterface()
{
}

/*
 * Implementation of interface class AuraDetectorInterfaceInterface
 */

AuraDetectorInterfaceInterface::AuraDetectorInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraDetectorInterfaceInterface::~AuraDetectorInterfaceInterface()
{
}

/*
 * Implementation of interface class AuraDisplayCTInterfaceInterface
 */

AuraDisplayCTInterfaceInterface::AuraDisplayCTInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraDisplayCTInterfaceInterface::~AuraDisplayCTInterfaceInterface()
{
}

/*
 * Implementation of interface class AuraGUIInterfaceInterface
 */

AuraGUIInterfaceInterface::AuraGUIInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraGUIInterfaceInterface::~AuraGUIInterfaceInterface()
{
}

/*
 * Implementation of interface class AuraWriterInterfaceInterface
 */

AuraWriterInterfaceInterface::AuraWriterInterfaceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AuraWriterInterfaceInterface::~AuraWriterInterfaceInterface()
{
}

